Create an RDD named `products` with `parallelize` containing the elements in the output.

In [1]:
products= sc.parallelize(["Apple", "Apple", "Cheese", "Apple", "Orange"])
products.collect()

['Apple', 'Apple', 'Cheese', 'Apple', 'Orange']

Count the number of elements in `products`

In [2]:
products.count()

5

Count the number of apples in `products`. Tip: use filter.

In [3]:
products.filter(lambda x:x == "Apple").count()

3

show the (distinct) products.

In [4]:
distinct=products.filter(lambda x:x).distinct().collect()
distinct

['Apple', 'Orange', 'Cheese']

Download the file babynames from https://health.data.ny.gov/api/views/jxy9-yhdk/rows.csv?accessType=DOWNLOAD, store the file locally and load its contents into a RDD called `babynames` with textFile. Show the first 5 lines.

In [5]:
babynamesrdd= sc.textFile('babynames.csv')
babynamesrdd.take(5)

['Year,First Name,County,Sex,Count',
 '2013,GAVIN,ST LAWRENCE,M,9',
 '2013,LEVI,ST LAWRENCE,M,9',
 '2013,LOGAN,NEW YORK,M,44',
 '2013,HUDSON,NEW YORK,M,49']

The first line in the file is a header, filter out the first line to keep only lines with actual data.

In [98]:
header= babynamesrdd.first()
geenheader=babynamesrdd.filter(lambda x:x !=header)
geenheader.take(5)

[['2013', 'LEVI', 'ST LAWRENCE', 'M', '9'],
 ['2013', 'LOGAN', 'NEW YORK', 'M', '44'],
 ['2013', 'HUDSON', 'NEW YORK', 'M', '49'],
 ['2013', 'GABRIEL', 'NEW YORK', 'M', '50'],
 ['2013', 'THEODORE', 'NEW YORK', 'M', '51']]

The elements in this RDD are each a line of text. Transform each element into a tuple or list that consists of the 5 columns in the csv by splitting the lines on comma characters. Show the first 5. Tip: you need `map` and the `split` method on Python Strings.

In [18]:
bob=babynamesrdd.map(lambda x:x.split(','))
bob.take(5)

[['Year', 'First Name', 'County', 'Sex', 'Count'],
 ['2013', 'GAVIN', 'ST LAWRENCE', 'M', '9'],
 ['2013', 'LEVI', 'ST LAWRENCE', 'M', '9'],
 ['2013', 'LOGAN', 'NEW YORK', 'M', '44'],
 ['2013', 'HUDSON', 'NEW YORK', 'M', '49']]

Count how many male babies are in the RDD.

In [60]:
babynamesrdd=bob.filter(lambda x:x[3] == "M")#.count() #667585
#print(babynamesrdd.take(5))
mapped = babynamesrdd.map(lambda x : (x[3],(x[4])))
print(mapped.take(5))
mapped.reduceByKey(lambda x, y : int(x) + int(y)).collect()
   
    
    
# #malebabymap.reducyByKey(lambda x, y: int(x) + (y))
# 
# #malebabymap.reducyByKey(lambda x, y: int(x) + (y))
# malebaby.take(5)                          
                           
                           
#malebaby.count()
#malebaby.describe()

[('M', '9'), ('M', '9'), ('M', '44'), ('M', '49'), ('M', '50')]

[('M', 667585)]

The next objective is to find the most given babyname.

First, convert the RDD into a key,value structure. Since we do not need anything but the name, we can convert every element into (name, 1). Show the first 5.

In [103]:
kvs=geenheader.map(lambda x: ((x[1]),(int(x[4]))))#.take(5)
kvs.collect()

[('LEVI', 9),
 ('LOGAN', 44),
 ('HUDSON', 49),
 ('GABRIEL', 50),
 ('THEODORE', 51),
 ('JONATHAN', 51),
 ('CHRISTOPHER', 52),
 ('LUKE', 49),
 ('JACKSON', 53),
 ('JACKSON', 49),
 ('JOSHUA', 53),
 ('AIDEN', 53),
 ('BRANDON', 50),
 ('MASON', 8),
 ('DAVID', 53),
 ('NOAH', 8),
 ('AIDEN', 8),
 ('SEBASTIAN', 57),
 ('SAMUEL', 59),
 ('MAX', 62),
 ('OLIVER', 66),
 ('JOSEPH', 66),
 ('JAYDEN', 66),
 ('LEO', 67),
 ('JOHN', 68),
 ('MICHAEL', 68),
 ('MASON', 69),
 ('MATTHEW', 76),
 ('CHARLES', 77),
 ('LIAM', 81),
 ('LIAM', 7),
 ('DYLAN', 85),
 ('DANIEL', 85),
 ('JAMES', 7),
 ('BENJAMIN', 86),
 ('HENRY', 87),
 ('RYAN', 92),
 ('LUCAS', 93),
 ('ETHAN', 97),
 ('JAMES', 99),
 ('WYATT', 7),
 ('JOSHUA', 50),
 ('LUCAS', 6),
 ('OLIVER', 6),
 ('JACOB', 100),
 ('JACK', 101),
 ('NOAH', 115),
 ('WILLIAM', 119),
 ('ALEXANDER', 123),
 ('DAVID', 51),
 ('BENJAMIN', 53),
 ('GAVIN', 54),
 ('AIDEN', 54),
 ('ETHAN', 56),
 ('LOGAN', 58),
 ('JAMES', 45),
 ('ELI', 6),
 ('LANDON', 6),
 ('CARSON', 6),
 ('ALEXANDER', 5),
 ('SAMUEL', 5),
 ('JACKSON', 5),
 ('HENRY', 5),
 ('NOAH', 60),
 ('JUSTIN', 63),
 ('CHRISTIAN', 63),
 ('LIAM', 70),
 ('THOMAS', 71),
 ('OWEN', 5),
 ('JOHN', 71),
 ('ANDREW', 74),
 ('JACK', 74),
 ('ANDREW', 47),
 ('CHASE', 5),
 ('BRAYDEN', 5),
 ('LINCOLN', 5),
 ('JASE', 5),
 ('JAYDEN', 74),
 ('LUCAS', 76),
 ('NOAH', 12),
 ('LOGAN', 9),
 ('LANDON', 9),
 ('RYAN', 48),
 ('LIAM', 7),
 ('ALEXANDER', 78),
 ('JACOB', 84),
 ('DANIEL', 87),
 ('CHRISTOPHER', 91),
 ('JAMES', 91),
 ('MASON', 97),
 ('RYAN', 100),
 ('DYLAN', 107),
 ('NICHOLAS', 125),
 ('ANTHONY', 128),
 ('JOSEPH', 129),
 ('MATTHEW', 132),
 ('MICHAEL', 142),
 ('BLAKE', 6),
 ('NOAH', 48),
 ('PARKER', 6),
 ('MASON', 48),
 ('BENJAMIN', 53),
 ('JOSEPH', 53),
 ('LIAM', 55),
 ('COLTON', 6),
 ('JAXON', 6),
 ('JACOB', 57),
 ('CHRISTOPHER', 59),
 ('MASON', 5),
 ('ALEXANDER', 5),
 ('RYAN', 5),
 ('JAMES', 5),
 ('SAMUEL', 5),
 ('GABRIEL', 5),
 ('GAVIN', 5),
 ('DAVID', 272),
 ('JAYDEN', 268),
 ('MOSHE', 219),
 ('JACOB', 202),
 ('ETHAN', 196),
 ('DANIEL', 188),
 ('ELI', 5),
 ('AIDEN', 182),
 ('BRANTLEY', 5),
 ('NOAH', 168),
 ('JOSEPH', 166),
 ('MICHAEL', 146),
 ('MATTHEW', 140),
 ('ABRAHAM', 135),
 ('SAMUEL', 133),
 ('LIAM', 130),
 ('JOSHUA', 130),
 ('ALEXANDER', 126),
 ('CHAIM', 126),
 ('RYAN', 124),
 ('ANTHONY', 122),
 ('ISAAC', 122),
 ('LUCAS', 118),
 ('DYLAN', 116),
 ('BENJAMIN', 110),
 ('MASON', 103),
 ('ELIJAH', 101),
 ('JUSTIN', 101),
 ('AARON', 99),
 ('KEVIN', 93),
 ('JAMES', 92),
 ('NATHAN', 91),
 ('CHRISTOPHER', 89),
 ('MARCELLO', 5),
 ('CARMINE', 5),
 ('YOSEF', 86),
 ('GABRIEL', 83),
 ('WILLIAM', 81),
 ('JEREMIAH', 80),
 ('SHIMON', 80),
 ('MUHAMMAD', 79),
 ('ADAM', 78),
 ('AMIR', 78),
 ('JASON', 77),
 ('CHRISTIAN', 76),
 ('FRANCESCO', 5),
 ('ANDREW', 75),
 ('SYED', 5),
 ('SERGIO', 5),
 ('JEFFERSON', 5),
 ('RONALD', 5),
 ('TYLER', 75),
 ('DERRICK', 5),
 ('FRANCIS', 5),
 ('SANTINO', 5),
 ('GARRETT', 5),
 ('EMANUEL', 5),
 ('JOSIAH', 75),
 ('NICHOLAS', 74),
 ('JONATHAN', 73),
 ('HENRY', 72),
 ('ERIC', 72),
 ('ELI', 71),
 ('JAYLEN', 5),
 ('CASEY', 5),
 ('MANUEL', 5),
 ('ANDRE', 5),
 ('ABEL', 5),
 ('CODY', 5),
 ('MOHAMMAD', 5),
 ('AHMED', 5),
 ('IBRAHIM', 5),
 ('RAFAEL', 5),
 ('DAMIAN', 5),
 ('ANDY', 5),
 ('LINCOLN', 5),
 ('CHAIM', 5),
 ('MOSHE', 5),
 ('BRANDON', 70),
 ('JOHN', 69),
 ('MORDECHAI', 68),
 ('MENACHEM', 65),
 ('JACK', 64),
 ('SEBASTIAN', 64),
 ('ARON', 63),
 ('YITZCHOK', 63),
 ('SHLOMO', 60),
 ('EVAN', 59),
 ('OLIVER', 59),
 ('OWEN', 58),
 ('ADRIAN', 58),
 ('GERARD', 6),
 ('AARAV', 6),
 ('GIUSEPPE', 6),
 ('LUCIANO', 6),
 ('FREDERICK', 6),
 ('DONOVAN', 6),
 ('DENNIS', 6),
 ('KIERAN', 6),
 ('LEO', 58),
 ('LOGAN', 57),
 ('AYAAN', 6),
 ('JUDAH', 6),
 ('NICO', 6),
 ('ARI', 6),
 ('SANTIAGO', 6),
 ('JULIAN', 56),
 ('ANGEL', 54),
 ('AUSTIN', 54),
 ('YISROEL', 54),
 ('JULIUS', 6),
 ('PHILIP', 6),
 ('SHMUEL', 6),
 ('YAKOV', 52),
 ('NATHANIEL', 51),
 ('YEHUDA', 51),
 ('ISAIAH', 50),
 ('JARED', 6),
 ('EMMETT', 6),
 ('MARTIN', 6),
 ('DAMIEN', 6),
 ('RAYMOND', 6),
 ('JUAN', 6),
 ('DEVIN', 6),
 ('MICAH', 6),
 ('OSCAR', 6),
 ('AMIR', 6),
 ('ABRAHAM', 6),
 ('PEYTON', 6),
 ('GIANLUCA', 7),
 ('NIKO', 7),
 ('MAX', 49),
 ('STEVEN', 49),
 ('JADEN', 49),
 ('LEVI', 48),
 ('YAAKOV', 48),
 ('SHMUEL', 47),
 ('CALEB', 46),
 ('MARIO', 7),
 ('JOHAN', 7),
 ('JORGE', 7),
 ('GREGORY', 7),
 ('JAMESON', 7),
 ('SAWYER', 7),
 ('ANDERSON', 7),
 ('ISRAEL', 7),
 ('RYDER', 7),
 ('CAYDEN', 7),
 ('CHARLES', 46),
 ('ZEV', 46),
 ('OSCAR', 45),
 ('ISRAEL', 45),
 ('XAVIER', 44),
 ('ALEX', 44),
 ('IVAN', 44),
 ('ALAN', 42),
 ('AVRAHAM', 42),
 ('LUKE', 41),
 ('LOUIS', 7),
 ('KENNETH', 7),
 ('ETHAN', 59),
 ('ANTHONY', 62),
 ('ROBERT', 41),
 ('BRIAN', 41),
 ('AYDEN', 40),
 ('GREYSON', 7),
 ('OMAR', 40),
 ('KAI', 7),
 ('KING', 7),
 ('ARIEL', 7),
 ('KYLE', 7),
 ('JOSE', 7),
 ('COLTON', 7),
 ('REID', 8),
 ('ROCCO', 8),
 ('SALVATORE', 8),
 ('TREVOR', 8),
 ('DIEGO', 8),
 ('JESSE', 8),
 ('BRADY', 8),
 ('MARK', 8),
 ('EMMANUEL', 8),
 ('MUHAMMAD', 8),
 ('AVERY', 8),
 ('CHRIS', 9),
 ('MYLES', 9),
 ('SPENCER', 9),
 ('EDWIN', 9),
 ('MAXIMUS', 9),
 ('AXEL', 9),
 ('PRESTON', 9),
 ('DEAN', 9),
 ('ASHER', 9),
 ('MATEO', 9),
 ('CARLOS', 9),
 ('JAXSON', 9),
 ('NOLAN', 9),
 ('LEVI', 9),
 ('ALEJANDRO', 10),
 ('EZRA', 10),
 ('NICHOLAS', 63),
 ('ALEXANDER', 63),
 ('MICHAEL', 66),
 ('DANIEL', 72),
 ('DYLAN', 74),
 ('MATTHEW', 85),
 ('VINCENT', 39),
 ('JOEL', 39),
 ('JOSE', 39),
 ('KAIDEN', 39),
 ('CARTER', 38),
 ('THEODORE', 38),
 ('ELIEZER', 38),
 ('JORDAN', 37),
 ('IAN', 37),
 ('TZVI', 36),
 ('ZACHARY', 35),
 ('KAYDEN', 35),
 ('RICHARD', 35),
 ('JACKSON', 34),
 ('CAMERON', 34),
 ('THOMAS', 33),
 ('TRISTAN', 33),
 ('MARCUS', 32),
 ('EZRA', 32),
 ('ZION', 32),
 ('LIPA', 32),
 ('CHASE', 31),
 ('GIOVANNI', 31),
 ('BRYAN', 31),
 ('SIMON', 31),
 ('MEIR', 31),
 ('SHULEM', 31),
 ('HUNTER', 30),
 ('JAKE', 30),
 ('JONAH', 10),
 ('KAIDEN', 10),
 ('HUDSON', 10),
 ('THEODORE', 10),
 ('MAXWELL', 10),
 ('LUCA', 30),
 ('MILES', 30),
 ('VICTOR', 11),
 ('COOPER', 11),
 ('DEREK', 11),
 ('TIMOTHY', 11),
 ('RICHARD', 11),
 ('EMMANUEL', 30),
 ('MENDEL', 30),
 ('KING', 29),
 ('MARCO', 12),
 ('CRISTIAN', 12),
 ('LORENZO', 12),
 ('BRADLEY', 12),
 ('MILES', 12),
 ('BRYAN', 12),
 ('JAXON', 12),
 ('FELIX', 29),
 ('JACE', 28),
 ('JEREMY', 28),
 ('KYLE', 28),
 ('VICTOR', 28),
 ('SOLOMON', 28),
 ('SIMCHA', 28),
 ('ANDY', 27),
 ('KADEN', 27),
 ('MAXWELL', 26),
 ('LUIS', 26),
 ('NICOLAS', 26),
 ('MARK', 26),
 ('MARTIN', 26),
 ('DOVID', 26),
 ('EDWARD', 25),
 ('AYDEN', 12),
 ('ELI', 12),
 ('SHANE', 13),
 ('FRANK', 13),
 ('HARRISON', 13),
 ('NICOLAS', 13),
 ('ANTONIO', 13),
 ('LUIS', 13),
 ('JADEN', 13),
 ('JOSUE', 14),
 ('JEFFREY', 14),
 ('DOMINICK', 14),
 ('PAUL', 14),
 ('BRYCE', 14),
 ('JOEL', 14),
 ('ISAIAH', 14),
 ('JEREMIAH', 14),
 ('ANGEL', 14),
 ('OLIVER', 14),
 ('MATTEO', 15),
 ('GEORGE', 15),
 ('GRAYSON', 15),
 ('KAYDEN', 15),
 ('SEAN', 25),
 ('ELIAS', 25),
 ('LEONARDO', 25),
 ('MICAH', 25),
 ('ALI', 25),
 ('MOHAMED', 25),
 ('MOHAMMAD', 25),
 ('MOHAMMED', 25),
 ('MOSES', 25),
 ('SAM', 25),
 ('SHIA', 25),
 ('YECHIEL', 25),
 ('HERSHY', 25),
 ('KAI', 24),
 ('RAYMOND', 24),
 ('GAVIN', 23),
 ('AIDAN', 23),
 ('ASHER', 23),
 ('ELLIOT', 23),
 ('AHMED', 23),
 ('LEON', 23),
 ('ARYEH', 23),
 ('USHER', 23),
 ('GEORGE', 22),
 ('JONAH', 22),
 ('RAFAEL', 22),
 ('PRINCE', 22),
 ('CARMELO', 5),
 ('JAX', 5),
 ('RORY', 5),
 ('BLAKE', 8),
 ('PARKER', 8),
 ('ABRAHAM', 8),
 ('GRAYSON', 8),
 ('BRODY', 8),
 ('EMMANUEL', 8),
 ('LEO', 15),
 ('PARKER', 15),
 ('JOSIAH', 15),
 ('ANGELO', 16),
 ('ASHTON', 16),
 ('LEONARDO', 16),
 ('EDWARD', 16),
 ('ERIC', 16),
 ('LANDON', 16),
 ('XAVIER', 16),
 ('IAN', 16),
 ('PETER', 17),
 ('GIOVANNI', 17),
 ('ISAAC', 17),
 ('COLE', 18),
 ('TRISTAN', 18),
 ('ALEX', 18),
 ('BRAYDEN', 18),
 ('BLAKE', 18),
 ('ADAM', 18),
 ('HENRY', 18),
 ('BRENDAN', 19),
 ('BRODY', 19),
 ('PATRICK', 20),
 ('ADRIAN', 20),
 ('CAMERON', 20),
 ('PAUL', 8),
 ('OSCAR', 8),
 ('JUAN', 8),
 ('ARTHUR', 22),
 ('NAFTALI', 22),
 ('CONNOR', 21),
 ('MALACHI', 21),
 ('AMARI', 21),
 ('ALVIN', 21),
 ('MILO', 21),
 ('DOV', 21),
 ('AVROHOM', 21),
 ('DOMINIC', 20),
 ('PATRICK', 20),
 ('PETER', 20),
 ('CARLOS', 20),
 ('HARRISON', 20),
 ('LOUIS', 20),
 ('AXEL', 8),
 ('ERICK', 8),
 ('GAEL', 8),
 ('SANTIAGO', 8),
 ('EDWIN', 20),
 ('JULIAN', 20),
 ('SEAN', 21),
 ('BRIAN', 21),
 ('JACE', 21),
 ('COLIN', 22),
 ('AIDAN', 22),
 ('MAX', 22),
 ('EVAN', 23),
 ('OWEN', 23),
 ('MESSIAH', 20),
 ('YUSUF', 20),
 ('AUGUST', 20),
 ('MAYER', 20),
 ('JEREMY', 24),
 ('CARTER', 24),
 ('DECLAN', 25),
 ('CONNOR', 26),
 ('CALEB', 26),
 ('HUNTER', 26),
 ('LUCA', 27),
 ('DEVIN', 19),
 ('STEVEN', 27),
 ('NATHANIEL', 27),
 ('VINCENT', 27),
 ('AUSTIN', 28),
 ('JORDAN', 28),
 ('KEVIN', 28),
 ('SEBASTIAN', 28),
 ('NATHAN', 28),
 ('DOMINIC', 29),
 ('ROBERT', 29),
 ('ELIJAH', 29),
 ('DAMIAN', 19),
 ('IBRAHIM', 19),
 ('CHASE', 30),
 ('CHARLES', 30),
 ('GAVIN', 30),
 ('JASON', 33),
 ('SAMUEL', 33),
 ('ZACHARY', 35),
 ('ERICK', 19),
 ('DANNY', 19),
 ('BRANDON', 36),
 ('THOMAS', 36),
 ('AARON', 37),
 ('GABRIEL', 40),
 ('DAVID', 40),
 ('JAKE', 42),
 ('JONATHAN', 42),
 ('JACKSON', 42),
 ('TYLER', 45),
 ('LUKE', 46),
 ('NOAH', 47),
 ('LOGAN', 49),
 ('JUSTIN', 51),
 ('JOSHUA', 53),
 ('JAYDEN', 56),
 ('JACK', 57),
 ('MASON', 57),
 ('AIDEN', 58),
 ('ANDREW', 59),
 ('JOHN', 60),
 ('WILLIAM', 60),
 ('LUCAS', 61),
 ('CHRISTIAN', 63),
 ('BENJAMIN', 64),
 ('ALEXANDER', 70),
 ('CHRISTOPHER', 75),
 ('ETHAN', 77),
 ('LIAM', 80),
 ('NICHOLAS', 82),
 ('JAMES', 86),
 ('DANIEL', 90),
 ('JACOB', 91),
 ('RYAN', 98),
 ('ANTHONY', 102),
 ('MICHAEL', 106),
 ('JOSEPH', 111),
 ('LAWRENCE', 19),
 ('BENZION', 19),
 ('WYATT', 18),
 ('TIMOTHY', 18),
 ('PRESTON', 18),
 ('ROMAN', 18),
 ('JESSE', 18),
 ('JESUS', 18),
 ('JASPER', 18),
 ('JAYLEN', 18),
 ('SAMIR', 18),
 ('HERSHEL', 18),
 ('AVERY', 17),
 ('NOLAN', 17),
 ('BRYCE', 17),
 ('DEREK', 17),
 ('HAYDEN', 17),
 ('MATEO', 17),
 ('MIGUEL', 17),
 ('CHARLIE', 17),
 ('JEFFREY', 17),
 ('NOEL', 17),
 ('NASIR', 17),
 ('AKIVA', 17),
 ('ELIYAHU', 17),
 ('EASON', 17),
 ('ELIMELECH', 17),
 ('YOSSI', 17),
 ('ANTONIO', 16),
 ('AXEL', 16),
 ('CRISTIAN', 16),
 ('JAIDEN', 16),
 ('CALVIN', 16),
 ('GREGORY', 16),
 ('ALBERT', 16),
 ('DARREN', 16),
 ('WILSON', 16),
 ('DYLAN', 114),
 ('MATTHEW', 121),
 ('SHAYA', 16),
 ('ANSON', 16),
 ('YEHOSHUA', 16),
 ('AVRUM', 16),
 ('SHOLOM', 16),
 ('JUAN', 15),
 ('KENNETH', 15),
 ('DIEGO', 15),
 ('JUDAH', 15),
 ('ABDULLAH', 15),
 ('STANLEY', 15),
 ('JERRY', 15),
 ('SHMIEL', 15),
 ('SHLOME', 15),
 ('LAZER', 15),
 ('PAUL', 14),
 ('CAYDEN', 14),
 ('MARCO', 14),
 ('JUDE', 14),
 ('ADEN', 14),
 ('JAVIER', 14),
 ('RANDY', 14),
 ('MALIK', 14),
 ('MAXIM', 14),
 ('KINGSLEY', 14),
 ('EFRAIM', 14),
 ('HERSH', 14),
 ('MEILECH', 14),
 ('RILEY', 13),
 ('BLAKE', 13),
 ('BRAYDEN', 13),
 ('GRAYSON', 13),
 ('DOMINICK', 13),
 ('EDEN', 13),
 ('JAYCE', 13),
 ('FRANK', 13),
 ('JARED', 13),
 ('SHAWN', 13),
 ('CAIDEN', 13),
 ('CHANCE', 13),
 ('ALLEN', 13),
 ('RICARDO', 13),
 ('JOHNNY', 13),
 ('AYAAN', 13),
 ('RAYAN', 13),
 ('BEN', 13),
 ('NELSON', 13),
 ('ZAIRE', 13),
 ('EDDIE', 13),
 ('ALEXIS', 12),
 ('DECLAN', 12),
 ('LORENZO', 12),
 ('ALEJANDRO', 12),
 ('WESLEY', 12),
 ('PHILIP', 12),
 ('JULIUS', 12),
 ('MAXIMILIAN', 12),
 ('JAYCEON', 12),
 ('ARI', 12),
 ('ARMANI', 12),
 ('SHEA', 12),
 ('MALCOLM', 12),
 ('HAMZA', 12),
 ('WINSTON', 12),
 ('YOEL', 12),
 ('AHARON', 12),
 ('MENDY', 12),
 ('MOISHE', 12),
 ('MEYER', 12),
 ('MORRIS', 12),
 ('PEYTON', 11),
 ('PARKER', 11),
 ('BRADLEY', 11),
 ('ASHTON', 11),
 ('SKYLER', 11),
 ('BRENDAN', 11),
 ('SPENCER', 11),
 ('MILAN', 11),
 ('GAEL', 11),
 ('SANTIAGO', 11),
 ('FINN', 11),
 ('KARTER', 11),
 ('JUSTICE', 11),
 ('IKER', 11),
 ('DESMOND', 11),
 ('FRANCISCO', 11),
 ('RAPHAEL', 11),
 ('JASIAH', 11),
 ('NEHEMIAH', 11),
 ('TONY', 11),
 ('LUCIEN', 11),
 ('THEO', 11),
 ('GAVRIEL', 11),
 ('UMAR', 11),
 ('NAFTULI', 11),
 ('BENSON', 11),
 ('BORUCH', 11),
 ('PINCHAS', 11),
 ('SHLOIME', 11),
 ('CHESKY', 11),
 ('COLIN', 10),
 ('STEPHEN', 10),
 ('EMMETT', 10),
 ('MYLES', 10),
 ('JOSUE', 10),
 ('EVERETT', 10),
 ('MARTIN', 7),
 ('CADEN', 10),
 ('EMANUEL', 10),
 ('CARMELO', 10),
 ('FERNANDO', 10),
 ('EDWIN', 7),
 ('ISMAEL', 10),
 ('JULIEN', 10),
 ('DAMIAN', 7),
 ('ALEC', 10),
 ('KAREEM', 10),
 ('BRAYAN', 10),
 ('AHMAD', 10),
 ('JIMMY', 10),
 ('ELVIS', 10),
 ('ALLAN', 10),
 ('JAMAL', 10),
 ('BARUCH', 10),
 ('NACHMAN', 10),
 ('TERRENCE', 10),
 ('DUVID', 10),
 ('YANKY', 10),
 ('ARYE', 10),
 ('SHNEUR', 10),
 ('EVAN', 7),
 ('LOGAN', 6),
 ('NOAH', 5),
 ('LIAM', 8),
 ('CARTER', 6),
 ('WYATT', 6),
 ('COLTON', 6),
 ('ETHAN', 5),
 ('NOAH', 5),
 ('LOGAN', 5),
 ('BLAKE', 5),
 ('THIAGO', 8),
 ('FRANCISCO', 8),
 ('RONAN', 8),
 ('ROMAN', 7),
 ('CHARLIE', 7),
 ('KING', 7),
 ('HARRISON', 5),
 ('ERIC', 7),
 ('MARC', 5),
 ('EDUARDO', 5),
 ('HUNTER', 5),
 ('BENJAMIN', 5),
 ('NOAH', 5),
 ('ELI', 6),
 ('JACOB', 6),
 ('MARQUIS', 5),
 ('SINCERE', 5),
 ('GAGE', 5),
 ('KINGSTON', 5),
 ('SANTINO', 5),
 ('GARRETT', 5),
 ('KEEGAN', 5),
 ('WALTER', 5),
 ('NASIR', 5),
 ('DANTE', 5),
 ('AHMED', 5),
 ('SHANE', 5),
 ('FRANK', 5),
 ('RAYMOND', 5),
 ('DEAN', 5),
 ('SKYLER', 5),
 ('CARSON', 5),
 ('EMMANUEL', 5),
 ('GEORGE', 5),
 ('ELIAS', 5),
 ('JOEL', 5),
 ('JUSTIN', 5),
 ('EZEQUIEL', 6),
 ('MALCOLM', 6),
 ('JADIEL', 6),
 ('COLLIN', 6),
 ('JAMESON', 6),
 ('KALEB', 6),
 ('ELLIOT', 6),
 ('ASHTON', 6),
 ('HARRISON', 6),
 ('VICTOR', 6),
 ('MARK', 6),
 ('DECLAN', 6),
 ('AMIR', 6),
 ('PATRICK', 6),
 ('AIDAN', 6),
 ('PEYTON', 6),
 ('ADAM', 6),
 ('AVERY', 6),
 ('LUKAS', 7),
 ('EMMETT', 7),
 ('SPENCER', 7),
 ('MALACHI', 7),
 ('DAMIEN', 7),
 ('WESLEY', 7),
 ('MAXIMUS', 7),
 ('GREYSON', 7),
 ('JASE', 7),
 ('LINCOLN', 7),
 ('CAMDEN', 7),
 ('LEONARDO', 7),
 ('KAIDEN', 7),
 ('GRAYSON', 7),
 ('MAXWELL', 7),
 ('TRISTAN', 7),
 ('HAYDEN', 5),
 ('LEVI', 5),
 ('NOAH', 6),
 ('STEVEN', 7),
 ('ERIC', 7),
 ('JAKE', 7),
 ('JACOB', 6),
 ('AYDEN', 7),
 ('GIANNI', 8),
 ('JAYCEON', 8),
 ('CAYDEN', 8),
 ('BENTLEY', 8),
 ('MICAH', 8),
 ('COOPER', 8),
 ('EDWARD', 8),
 ('BRIAN', 8),
 ('WILLIAM', 49),
 ('LIAM', 48),
 ('MICHAEL', 44),
 ('JACKSON', 42),
 ('JACOB', 40),
 ('LEO', 8),
 ('IAN', 8),
 ('ANGEL', 8),
 ('MASON', 40),
 ('ETHAN', 39),
 ('SAWYER', 9),
 ('SILAS', 9),
 ('BRADY', 9),
 ('BRODY', 9),
 ('KYLE', 9),
 ('JOSE', 9),
 ('COLTON', 9),
 ('JACE', 9),
 ('LANDON', 9),
 ('LUKE', 9),
 ('KEVIN', 9),
 ('ROMAN', 10),
 ('ASHER', 10),
 ('JAXSON', 10),
 ('MILES', 10),
 ('ANTONIO', 10),
 ('THEODORE', 10),
 ('MAX', 10),
 ('JORDY', 5),
 ('JAMES', 39),
 ('JOHN', 36),
 ('LOGAN', 35),
 ('NOAH', 32),
 ('ALEXANDER', 32),
 ('DOMINIC', 32),
 ('RYAN', 31),
 ('NATHAN', 31),
 ('LUCAS', 30),
 ('JACK', 30),
 ('HENRY', 30),
 ('JAYDEN', 29),
 ('BENJAMIN', 29),
 ('ANTHONY', 28),
 ('CHARLES', 28),
 ('CAMERON', 28),
 ('CALEB', 27),
 ('COLIN', 27),
 ('XAVIER', 10),
 ('ZACHARY', 10),
 ('JONAH', 11),
 ('JOSEPH', 26),
 ('NICHOLAS', 25),
 ('JOSIAH', 25),
 ('JOSHUA', 24),
 ('SAMUEL', 24),
 ('CARTER', 24),
 ('CONNOR', 24),
 ('ANDREW', 23),
 ('OWEN', 23),
 ('JAXON', 11),
 ('LUCA', 11),
 ('LEVI', 11),
 ('ELI', 11),
 ('AUSTIN', 11),
 ('KING', 12),
 ('NOLAN', 12),
 ('EVAN', 23),
 ('THOMAS', 23),
 ('BLAKE', 22),
 ('DANIEL', 21),
 ('AIDEN', 20),
 ('CHASE', 20),
 ('PARKER', 20),
 ('ISAIAH', 20),
 ('MATTHEW', 19),
 ('ELIJAH', 19),
 ('OLIVER', 19),
 ('VINCENT', 19),
 ('COLE', 12),
 ('GIOVANNI', 12),
 ('HUNTER', 12),
 ('GAVIN', 18),
 ('GABRIEL', 17),
 ('CHRISTIAN', 17),
 ('JONATHAN', 17),
 ('JASON', 17),
 ('TYLER', 16),
 ('BRANDON', 12),
 ('AARON', 12),
 ('SEBASTIAN', 16),
 ('JEREMIAH', 16),
 ('DAVID', 12),
 ('TIMOTHY', 13),
 ('KAYDEN', 13),
 ('WYATT', 13),
 ('ADRIAN', 13),
 ('ROBERT', 13),
 ('BRAYDEN', 14),
 ('NATHANIEL', 14),
 ('JORDAN', 14),
 ('CHRISTOPHER', 15),
 ('ISAAC', 15),
 ('DYLAN', 14),
 ('JULIAN', 14),
 ('JOHN', 25),
 ('NOAH', 25),
 ('ALEXANDER', 29),
 ('MASON', 32),
 ('MATTHEW', 33),
 ('JACE', 5),
 ('MATTHEW', 18),
 ('JACKSON', 18),
 ('LUCAS', 16),
 ('CHRISTOPHER', 34),
 ('BLAKE', 5),
 ('THOMAS', 5),
 ('JAMES', 35),
 ('DANIEL', 47),
 ('ANTHONY', 52),
 ('NICHOLAS', 54),
 ('TYLER', 5),
 ('CARTER', 5),
 ('LOGAN', 5),
 ('ANTHONY', 5),
 ('LUKE', 11),
 ('NOAH', 15),
 ('RYAN', 15),
 ('JOSEPH', 68),
 ('MICHAEL', 68),
 ('JASON', 13),
 ('GABRIEL', 13),
 ('LOGAN', 15),
 ('MICHAEL', 14),
 ('LEO', 9),
 ('CHRISTOPHER', 14),
 ('LIAM', 13),
 ('ALEXANDER', 13),
 ('JOHN', 13),
 ('JACOB', 12),
 ('JACK', 12),
 ('CARTER', 12),
 ('OWEN', 12),
 ('ANTHONY', 11),
 ('BENJAMIN', 11),
 ('BRODY', 5),
 ('GIOVANNI', 14),
 ('WYATT', 9),
 ('EVAN', 11),
 ('OLIVER', 11),
 ('JAMES', 10),
 ('NICHOLAS', 10),
 ('GAVIN', 10),
 ('THOMAS', 10),
 ('CONNOR', 10),
 ('JAYDEN', 9),
 ('DANIEL', 9),
 ('JOSHUA', 9),
 ('JONATHAN', 9),
 ('HENRY', 9),
 ...]

Now you can aggregate the elements that have the same key, and sum the values to get the number of occurrences per name. Show the first 5, these might be different ones than displayed below. Tip: use `reduceByKey`

In [104]:
a=kvs.reduceByKey().mapValues(sum).take(5)

#????????????????????????????????
#answer= 
# [('GAVIN', 262),
#  ('LEVI', 148),
#  ('LOGAN', 386),
#  ('HUDSON', 100),
#  ('GABRIEL', 243)]

TypeError: reduceByKey() missing 1 required positional argument: 'func'

Now `map` the name,frequency pairs so that you only have the values and use the `max` action to get the highest value.

In [133]:
maximum= geenheader.map(lambda x: (int(x[4])))
print(maximum.max())
maximum.collect()

#answer 
#386

297

[9,
 44,
 49,
 50,
 51,
 51,
 52,
 49,
 53,
 49,
 53,
 53,
 50,
 8,
 53,
 8,
 8,
 57,
 59,
 62,
 66,
 66,
 66,
 67,
 68,
 68,
 69,
 76,
 77,
 81,
 7,
 85,
 85,
 7,
 86,
 87,
 92,
 93,
 97,
 99,
 7,
 50,
 6,
 6,
 100,
 101,
 115,
 119,
 123,
 51,
 53,
 54,
 54,
 56,
 58,
 45,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 60,
 63,
 63,
 70,
 71,
 5,
 71,
 74,
 74,
 47,
 5,
 5,
 5,
 5,
 74,
 76,
 12,
 9,
 9,
 48,
 7,
 78,
 84,
 87,
 91,
 91,
 97,
 100,
 107,
 125,
 128,
 129,
 132,
 142,
 6,
 48,
 6,
 48,
 53,
 53,
 55,
 6,
 6,
 57,
 59,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 272,
 268,
 219,
 202,
 196,
 188,
 5,
 182,
 5,
 168,
 166,
 146,
 140,
 135,
 133,
 130,
 130,
 126,
 126,
 124,
 122,
 122,
 118,
 116,
 110,
 103,
 101,
 101,
 99,
 93,
 92,
 91,
 89,
 5,
 5,
 86,
 83,
 81,
 80,
 80,
 79,
 78,
 78,
 77,
 76,
 5,
 75,
 5,
 5,
 5,
 5,
 75,
 5,
 5,
 5,
 5,
 5,
 75,
 74,
 73,
 72,
 72,
 71,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 70,
 69,
 68,
 65,
 64,
 64,
 63,
 63,
 60,
 59,
 59,
 58,
 58,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 58,
 57,
 6,
 6,
 6,
 6,
 6,
 56,
 54,
 54,
 54,
 6,
 6,
 6,
 52,
 51,
 51,
 50,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 49,
 49,
 49,
 48,
 48,
 47,
 46,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 46,
 46,
 45,
 45,
 44,
 44,
 44,
 42,
 42,
 41,
 7,
 7,
 59,
 62,
 41,
 41,
 40,
 7,
 40,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 63,
 63,
 66,
 72,
 74,
 85,
 39,
 39,
 39,
 39,
 38,
 38,
 38,
 37,
 37,
 36,
 35,
 35,
 35,
 34,
 34,
 33,
 33,
 32,
 32,
 32,
 32,
 31,
 31,
 31,
 31,
 31,
 31,
 30,
 30,
 10,
 10,
 10,
 10,
 10,
 30,
 30,
 11,
 11,
 11,
 11,
 11,
 30,
 30,
 29,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 29,
 28,
 28,
 28,
 28,
 28,
 28,
 27,
 27,
 26,
 26,
 26,
 26,
 26,
 26,
 25,
 12,
 12,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 15,
 15,
 15,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 24,
 24,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 22,
 22,
 22,
 22,
 5,
 5,
 5,
 8,
 8,
 8,
 8,
 8,
 8,
 15,
 15,
 15,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 17,
 17,
 17,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 19,
 19,
 20,
 20,
 20,
 8,
 8,
 8,
 22,
 22,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 20,
 20,
 20,
 20,
 20,
 20,
 8,
 8,
 8,
 8,
 20,
 20,
 21,
 21,
 21,
 22,
 22,
 22,
 23,
 23,
 20,
 20,
 20,
 20,
 24,
 24,
 25,
 26,
 26,
 26,
 27,
 19,
 27,
 27,
 27,
 28,
 28,
 28,
 28,
 28,
 29,
 29,
 29,
 19,
 19,
 30,
 30,
 30,
 33,
 33,
 35,
 19,
 19,
 36,
 36,
 37,
 40,
 40,
 42,
 42,
 42,
 45,
 46,
 47,
 49,
 51,
 53,
 56,
 57,
 57,
 58,
 59,
 60,
 60,
 61,
 63,
 64,
 70,
 75,
 77,
 80,
 82,
 86,
 90,
 91,
 98,
 102,
 106,
 111,
 19,
 19,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 114,
 121,
 16,
 16,
 16,
 16,
 16,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 10,
 10,
 10,
 10,
 10,
 10,
 7,
 10,
 10,
 10,
 10,
 7,
 10,
 10,
 7,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 7,
 6,
 5,
 8,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 8,
 8,
 8,
 7,
 7,
 7,
 5,
 7,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 5,
 5,
 6,
 7,
 7,
 7,
 6,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 49,
 48,
 44,
 42,
 40,
 8,
 8,
 8,
 40,
 39,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 5,
 39,
 36,
 35,
 32,
 32,
 32,
 31,
 31,
 30,
 30,
 30,
 29,
 29,
 28,
 28,
 28,
 27,
 27,
 10,
 10,
 11,
 26,
 25,
 25,
 24,
 24,
 24,
 24,
 23,
 23,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 23,
 23,
 22,
 21,
 20,
 20,
 20,
 20,
 19,
 19,
 19,
 19,
 12,
 12,
 12,
 18,
 17,
 17,
 17,
 17,
 16,
 12,
 12,
 16,
 16,
 12,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 15,
 15,
 14,
 14,
 25,
 25,
 29,
 32,
 33,
 5,
 18,
 18,
 16,
 34,
 5,
 5,
 35,
 47,
 52,
 54,
 5,
 5,
 5,
 5,
 11,
 15,
 15,
 68,
 68,
 13,
 13,
 15,
 14,
 9,
 14,
 13,
 13,
 13,
 12,
 12,
 12,
 12,
 11,
 11,
 5,
 14,
 9,
 11,
 11,
 10,
 10,
 10,
 10,
 10,
 9,
 9,
 9,
 9,
 9,
 ...]

And revert back to the name,frequency pairs and filter the pair(s) that have a frequency equal to the max you found.

In [171]:
aa= kvs.filter( lambda x: x[1]== 297)
aa.collect()
#answer=
#[('LOGAN', 386)]

[('DAVID', 297)]